# Copyright 2024 TRAPS

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: docker-build-ros2-pkg
description: Build Docker Image for ROS2 package and push to ghcr.io

inputs:
  token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
  platforms:
    description: Docker Image platform (comma separation)
    required: false
    default: linux/amd64, linux/arm64/v8
  rosdistro:
    description: ROS distribution (lowercase)
    required: false
    default: humble

runs:
  using: composite
  steps:
  - name: Login to GitHub Container Registry
    run: echo ${{ inputs.platforms }}
      
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v3.4.0
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ github.token }}
      logout: false

  - name: Extract metadata (tags, labels) for Docker
    id: set-docker-metadata
    uses: docker/metadata-action@v5.7.0
    with:
      images: ghcr.io/${{ github.repository }}
  
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v3.6.0
    # with:
    #   platforms: ${{ inputs.platforms }}

  - name: Set up Docker Buildx
    id: set-docker-builder
    uses: docker/setup-buildx-action@v3.10.0
    # with:
    #   platforms: ${{ inputs.platforms }}

  - name: Build and push
    uses: docker/build-push-action@v6.15.0
    with:
      context: ${{ github.action_path }}
      file: ${{ github.action_path }}/Dockerfile
      push: true
      tags: ${{ steps.set-docker-metadata.outputs.tags }}
      labels: ${{ steps.set-docker-metadata.outputs.labels }}
      build-args: |
        ROS_DISTRO=${{ inputs.rosdistro }}
        ENTRYPOINT_FILE=ros_ws_entrypoint.sh
        GIT_REPOSITORY_NAME=${{ github.event.repository.name }}
        GIT_REMOTE_URL=https://github.com/${{ github.repository }}.git
        GIT_SHA=${{ github.sha }}
        PRE_IMPORT_SCRIPT=git config --global url.https://${{ inputs.token }}@github.com.insteadOf https://github.com
        BUILD_OPTIONS=--cmake-args -DCMAKE_BUILD_TYPE=Release --parallel-workers 1
      platforms: ${{ inputs.platforms }}
      builder: ${{ steps.set-docker-builder.outputs.name }}
      cache-from: type=gha
      cache-to: type=gha, mode=max
