name: "Updated: colcon-test"

run-name: "Updated: colcon-test: ${{ github.ref_name }}(${{ github.event.head_commit.message }})"

on:
  push:
    paths:
      - "colcon-test/**"
      - ".github/workflows/updated-colcon-test.yaml"
  pull_request:
    paths:
      - "colcon-test/**"
      - ".github/workflows/updated-colcon-test.yaml"

jobs:
  test-colcon-test-action:
    runs-on: ubuntu-22.04

    permissions:
      packages: read

    container:
      image: ros:humble-ros-base

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .traps-github-action

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: TRAPS-Robocup/traps_tools_ros
          path: ros2_ws/src/traps_tools_ros
      
      - name: Colcon test
        uses: ./.traps-github-action/colcon-test
        with:
          checkout: false
