name: "Updated: Get depends installer"

run-name: "Updated: Get depends installer:${{ github.ref_name }}(${{ github.event.head_commit.message }})"

on:
  push:
    paths:
      - "get-depends-installer/**"
      - ".github/workflows/updated-get-depends-installer.yaml"
  pull_request:
    paths:
      - "get-depends-installer/**"
      - ".github/workflows/updated-get-depends-installer.yaml"

jobs:
  test-get-depends-installer-action:
    runs-on: ubuntu-22.04

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .traps-github-action
      
      - name: Get depends install scripts
        id: get-depends-installer
        uses: ./.traps-github-action/get-depends-installer
      
      - name: Docker Build Packages
        uses: ./.traps-github-action/docker-build-pkg
        with:
          builder-base-image: ros:humble-ros-base
          executor-base-image: ros:humble-ros-core
          build-depends-install-script: ${{ steps.get-depends-installer.outputs.build-install-script }}
          pre-build-script: . /opt/ros/humble/setup.sh
          post-build-script: rm -rf log
          exec-depends-install-script: ${{ steps.get-depends-installer.outputs.exec-install-script }}
          push: false
          
